In [2]:
#1-Practice of scalar-based backpropagation
import numpy as np

# Define the function f(x, w)
def f(x1, x2, w1, w2):
    denominator = 2 + np.sin(x1 * w1) ** 2 + np.cos(x2 * w2)
    return 1.0 / denominator

# Define the gradient computation function
def compute_gradients(x1, x2, w1, w2):
    denominator = 2 + np.sin(x1 * w1) ** 2 + np.cos(x2 * w2)
    df_dw1 = -(2 * x1 * w1 * np.sin(x1 * w1) * np.cos(x1 * w1)) / (denominator ** 2)
    df_dw2 = (x2 * w2 * np.sin(x2 * w2)) / (denominator ** 2)
    return df_dw1, df_dw2

# Set values for inputs x1, x2, w1, and w2
x1 = 0.5
x2 = 1.0
w1 = 2.0
w2 = 1.5

# Calculate the function value
result = f(x1, x2, w1, w2)

# Compute the gradients
gradients = compute_gradients(x1, x2, w1, w2)

# Print the results
print("f(x, w) =", result)
print("df/dw1 =", gradients[0])
print("df/dw2 =", gradients[1])

f(x, w) = 0.3598661934080033
df/dw1 = -0.1177573604042027
df/dw2 = 0.19376890306779226


In [2]:
#2-Practice of vector-based backpropagation
import numpy as np

# Define the sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the function f(x, w)
def f(x, W):
    return np.linalg.norm(sigmoid(np.dot(W, x)))**2

# Define the gradient computation function
def compute_gradients(x, W):
    z = np.dot(W, x)
    sigmoid_z = sigmoid(z)
    squared_norm = np.linalg.norm(sigmoid_z)**2
    grad_W = 2 * np.outer(sigmoid_z * (1 - sigmoid_z), x)
    return grad_W

# Set values for the input x and weight matrix W
x = np.array([0.1, 0.2, 0.3])
W = np.random.rand(3, 3)  # Initialize W with random values

# Calculate the function value
result = f(x, W)

# Compute the gradients
gradients = compute_gradients(x, W)

# Print the results
print("f(x, W) =", result)
print("Gradients with respect to W:")
print(gradients)

f(x, W) = 0.9860061236817519
Gradients with respect to W:
[[0.04899499 0.09798998 0.14698497]
 [0.04884572 0.09769144 0.14653715]
 [0.04893361 0.09786721 0.14680082]]
